version: "3.1"

services:
    webserver:
      image: nginx:stable-alpine
      container_name: test-webserver
      working_dir: /var/www/app
      ports:
        - "8080:80"
      volumes:
        - .:/var/www/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    app:
      build: ./docker/php-fpm
      container_name: test-app
      working_dir: /var/www/app
      volumes:
        - .:/var/www/app
    mysql:
      image: mysql:5.7.22
      container_name: test-mysql
      working_dir: /var/www/app
      volumes:
#        - ./mysqldata:/var/lib/mysql
        - ./docker/mysql:/etc/mysql/conf.d
      ports:
        - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test
